name:                haskell-zoho
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/haskell-zoho#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hoauth2
  - uri-bytestring
  - bytestring
  - text
  - string-conv
  - http-client
  - http-client-tls
  - http-types
  - wreq
  - lens
  - lens-aeson
  - aeson
  - aeson-casing
  - time
  - generic-deriving
  - mtl
  - containers
  - unordered-containers
  - retry
  - exceptions
  - text-conversions
  - unliftio
  - unliftio-core
  - token-bucket
  - case-insensitive

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - ScopedTypeVariables
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards
  - DataKinds
  - FlexibleInstances
  - QuasiQuotes
  - DeriveGeneric
  - MultiParamTypeClasses
  - FunctionalDependencies
  - FlexibleContexts
  - DerivingVia

library:
  source-dirs:
    - src
  exposed-modules:
    - Zoho.Desk.Account
    - Zoho.Desk.Common
    - Zoho.Desk.Contact
    - Zoho.Desk.Types
    - Zoho.Desk.Utils
    - Zoho.OAuth
    - Zoho.Types
    - Zoho.ZohoM
    - Zoho.Books.Contact
    - Zoho.Books.Account
    - Zoho.Books.Expense
    - Zoho.Books.Bill
    - Zoho.Books.Common
    - Zoho.Books.Invoice
    - Zoho.Books.CreditNote
    - Zoho.Books.VendorPayment
    - Zoho.Books.CustomerPayment
    - Zoho.Books.VendorCredit
    - Zoho.Books.Journal
    - Zoho.Books.Item
    - Zoho.CRM.Records
    - Zoho.CRM.Common
    - Zoho.CRM.Contacts
    - Zoho.CRM.Accounts
    - Zoho.CRM.COQL
    - Zoho.CRM.Activities
    - Zoho.CRM.Users
    - Zoho.CRM.Notes
    - Zoho.Desk.Ticket
    - Zoho.Desk.Thread
    - Zoho.Desk.IM
    - Zoho.Desk.Conversation
    - Zoho.Desk.Article
    - Zoho.CRM.Common.Utils
