name:                haskell-zoho
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/haskell-zoho#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hoauth2
  - uri-bytestring
  - bytestring
  - text
  - string-conv
  - http-client
  - http-client-tls
  - http-types
  - wreq
  - lens
  - lens-aeson
  - aeson
  - aeson-casing
  - time
  - generic-deriving
  - mtl
  - containers
  - unordered-containers
  - retry
  - exceptions
  - text-conversions
  - connection
  - unliftio
  - unliftio-core

default-extensions:
  - TemplateHaskell
  - OverloadedStrings
  - ScopedTypeVariables
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards
  - DataKinds
  - FlexibleInstances
  - QuasiQuotes
  - DeriveGeneric
  - MultiParamTypeClasses
  - FunctionalDependencies
  - FlexibleContexts

library:
  source-dirs:
    - src
  exposed-modules:
    - Zoho.Desk.Account
    - Zoho.Desk.Common
    - Zoho.Desk.Contact
    - Zoho.Desk.Types
    - Zoho.Desk.Utils
    - Zoho.OAuth
    - Zoho.Types
    - Zoho.ZohoM


